love:
	-rm report.pdf
	pdflatex -shell-escape report.tex
	pdflatex -shell-escape report.tex
	rm -rf *.aux *.out *.log *.toc _minted-report

clean:
	-rm report.pdf
	-rm -rf *.aux *.out *.log *.pyg *.toc _minted-report

